export const USER_PRODUCT_REQUEST = "USER_PRODUCT_REQUEST";
export const USER_PRODUCT_REQUEST_SUCCESS = "USER_PRODUCT_REQUEST_SUCCESS";
export const USER_PRODUCT_REQUEST_ERROR = "USER_PRODUCT_REQUEST_ERROR";
export const USER_SELECTED_PRODUCT = "USER_SELECTED_PRODUCT";
export const USER_REMOVED_PRODUCT = "USER_REMOVED_PRODUCT";
